README.md

This should link to okhttp not okio

fix okhttp link

---

.travis.yml
README.md
build.gradle
stetho-okhttp/build.gradle
stetho/build.gradle

Fix `gradle connectedCheck`, then add `.travis.yml`.  Tested to work with Travis-CI against https://github.com/jasta/stetho

Integrate with Travis-CI

---

index.html

Follow-up from #29.  Eventually this will be the source of truth and we'll pull a lot of this
extra documentation from README.md.

Modify gh-pages to match #29

---

scripts/stetho_open.py

stetho_open.py naively assumes any entry matching @stetho_* represents a
bound server socket, however this is not true.  Connected client sockets
will also appear with different flags and in a different state.  Filter
based on this criteria to only identify server sockets.
Closes #37

Fix duplicate dumpapp endpoints for a single process

---

gradle.properties

Should've done this as part of the initial 1.0.0 release.  Will need to
automate the release process soon.

Bump to 1.0.1-SNAPSHOT.

---

stetho/src/main/java/com/facebook/stetho/common/ProcessUtil.java
stetho/src/main/java/com/facebook/stetho/inspector/ChromeDiscoveryHandler.java
stetho/src/main/java/com/facebook/stetho/inspector/protocol/module/Page.java
stetho/src/main/java/com/facebook/stetho/server/LocalSocketHttpServer.java

Add process name to chrome://inspect UI

---

stetho/src/main/java/com/facebook/stetho/Stetho.java
stetho/src/main/java/com/facebook/stetho/dumpapp/plugins/SharedPreferencesDumperPlugin.java
stetho/src/main/java/com/facebook/stetho/inspector/domstorage/DOMStoragePeerManager.java
stetho/src/main/java/com/facebook/stetho/inspector/domstorage/SharedPreferencesHelper.java
stetho/src/main/java/com/facebook/stetho/inspector/protocol/module/DOMStorage.java
stetho/src/main/java/com/facebook/stetho/inspector/protocol/module/Page.java
stetho/src/main/java/com/facebook/stetho/json/ObjectMapper.java
stetho/src/test/java/com/facebook/stetho/json/ObjectMapperTest.java

Add SharedPreferences data to Resources tab

---

stetho/src/main/java/com/facebook/stetho/common/android/ApplicationUtil.java
stetho/src/main/java/com/facebook/stetho/inspector/elements/android/ApplicationDescriptor.java
stetho/src/main/java/com/facebook/stetho/inspector/elements/android/ViewHighlighter.java
stetho/src/main/java/com/facebook/stetho/inspector/elements/android/WindowDescriptor.java
stetho/src/main/java/com/facebook/stetho/inspector/protocol/module/DOM.java

This should fix the NPE. I also fixed up my LogUtil usage in nearby code.
Closes #83

Fix to avoid NPE in DOM.ProviderListener.onChildRemoved

---

release.gradle

This corrects invalid javadoc jars uploaded to Maven for future
releases.

Fix androidJavadocJar

---

.idea/codeStyleSettings.xml
.idea/copyright/Facebook.xml
.idea/copyright/profiles_settings.xml
.idea/encodings.xml

This establishes formatting norms and adds the Copyright enforcement.

Add IntelliJ / Android Studio project files.

---

stetho/src/main/java/com/facebook/stetho/inspector/helper/ObjectIdMapper.java
stetho/src/main/java/com/facebook/stetho/inspector/protocol/module/DOM.java
stetho/src/main/java/com/facebook/stetho/inspector/protocol/module/Runtime.java

With this, developers can explore the Java object structure live from
Stetho as if a traditional debugger was attached.  This UI is a bit
buried and hard to notice, but can be found by clicking on an element in
the Elements tab and then finding the Properties tab on the right-hand
panel.  It is sometimes hidden behind a "more options"-style button.

Implement Elements, Properties sub-tab

---

stetho/src/main/java/com/facebook/stetho/inspector/helper/ObjectIdMapper.java
stetho/src/main/java/com/facebook/stetho/inspector/protocol/module/DOM.java

Fix for NPE crash in ApplicationDescriptor

---

README.md

This is redundantly described at https://facebook.github.io/stetho.
Prefer that high-level documentation where possible.  Especially
relevant since we're about to modify it with the Elements tab support :)

Remove "Features" section from README.

---

PATENTS

See:
https://code.facebook.com/posts/1639473982937255/updating-our-open-source-patent-grant/

Update patent grant

---

stetho/src/main/java/com/facebook/stetho/inspector/protocol/module/Database.java

The protocol asks for a list of databases first then allows the user to
expand that at any later time to a list of tables.  The database may
have been removed however and there is seemingly no protocol support for
communicating this removal.  We have no choice but to yield a JSON-RPC
error.
Closes #154

Work around a subtle race condition in Database.getDatabaseTableNames

---

stetho/src/main/java/com/facebook/stetho/inspector/protocol/module/DOM.java

Fix minor gotchas in DOM.resolveNode

---

stetho/src/main/java/com/facebook/stetho/dumpapp/StreamFramer.java

Dumpapp requests were prone to premature stream closer causing end-user error output. Overriding `close()` instead of forwarding control to `FilterOutputStream` resolves the issue and helps prevent similar hard to debug issues.

Resolved premature stream closure issue

---

stetho/src/main/java/com/facebook/stetho/Stetho.java
stetho/src/main/java/com/facebook/stetho/dumpapp/plugins/FilesDumperPlugin.java

Introduce a new standard dumper which allows developers to conveniently
extract application internal files.  Sample usage transcript:
https://gist.github.com/8d3280e16acbf12a59a5

Add FilesDumperPlugin

---

README.md

Mainly for the convenience of GitHub users.

README: Link to project files

---

stetho/src/main/java/com/facebook/stetho/inspector/protocol/module/DOM.java

The search searches node names, property names, and property values, mirroring the search in chrome inspect on an html webpage.
Closes #179

Added the ability to search the DOM tree

---

stetho/src/main/java/com/facebook/stetho/inspector/database/DatabasePeerManager.java
stetho/src/main/java/com/facebook/stetho/inspector/database/DefaultDatabaseFilesProvider.java
stetho/src/main/java/com/facebook/stetho/inspector/domstorage/SharedPreferencesHelper.java

The entries in this list can be quite large and hard to find.  Sorting
helps.
Closes #201

Sort DOMStorage entries (database and shared prefs)

---

README.md
stetho-sample/src/debug/java/com/facebook/stetho/sample/SampleDebugApplication.java
stetho/src/main/java/com/facebook/stetho/Stetho.java

Now that many more configuration options are becoming available it's
important to provide a more streamlined API for overriding plugins or
adding new ones, especially for dumpapp.
Closes #195

Provide a better customization API for Stetho.initialize

---

stetho/src/main/java/com/facebook/stetho/common/Util.java
stetho/src/main/java/com/facebook/stetho/inspector/network/AsyncPrettyPrinter.java
stetho/src/main/java/com/facebook/stetho/inspector/network/AsyncPrettyPrinterExecutorHolder.java
stetho/src/main/java/com/facebook/stetho/inspector/network/AsyncPrettyPrinterFactory.java
stetho/src/main/java/com/facebook/stetho/inspector/network/AsyncPrettyPrinterRegistry.java
stetho/src/main/java/com/facebook/stetho/inspector/network/DownloadingAsyncPrettyPrinterFactory.java
stetho/src/main/java/com/facebook/stetho/inspector/network/NetworkEventReporterImpl.java
stetho/src/main/java/com/facebook/stetho/inspector/network/NetworkPeerManager.java
stetho/src/main/java/com/facebook/stetho/inspector/network/PrettyPrinterDisplayType.java
stetho/src/main/java/com/facebook/stetho/inspector/network/ResponseBodyFileManager.java
stetho/src/main/java/com/facebook/stetho/inspector/network/TestAsyncPrettyPrinterFactory.java
stetho/src/main/java/com/facebook/stetho/inspector/protocol/module/Network.java
stetho/src/test/java/com/facebook/stetho/inspector/network/AsyncPrettyPrintResponseBodyTest.java

This PR provides the necessary interfaces and abstract class that provide the asynchronous pretty printing mechanism for stetho.

Add async pretty printing binary payload

---

stetho/src/main/java/com/facebook/stetho/inspector/elements/Document.java

I'm fixing this by turning it into a soft error. `Descriptor`s shouldn't emit null from their `getChildren` implementation, but it's easy enough to recover from this and at least not crash the app. This is the only place where the children are funneled out of `Descriptor` and into `Document`.
Closes #272

Fixing NPE crash in ElementInfo.<init>() from Document.createDOMUpdate()

---

stetho/src/main/java/com/facebook/stetho/inspector/elements/android/ViewDescriptor.java

I briefly explored doing this in a more generic way using the `ViewDebug.ExportedProperty#deepExport()` option, as it was specifically designed for the case where properties that we care about are nested in fields/method return values. However I found that really the only thing we *would* care about is the margin, so wrangling `deepExport`ed props wouldn't be worth the effort.
EDIT: Actually now I just use `deepExport`ed properties and special case margins so that they are displayed in the box-model.
Here's a screenshot with the margin visible in text form (highlighted by me) and in the box-model:

Added margins to css styles tab.

---

stetho-js-rhino/src/main/java/com/facebook/stetho/rhino/JsRuntimeRepl.java
stetho-js-rhino/src/main/java/com/facebook/stetho/rhino/JsRuntimeReplFactoryBuilder.java

Add support for [$_ as Google Chrome](https://developer.chrome.com/devtools/docs/commandline-api#_) does.

Save the last evalutate expression to $_ (as google chrome does)

---

.idea/codeStyleSettings.xml
.idea/encodings.xml

These look to be unimportant but Studio insists :)

Apply random Android Studio 2.0 project changes

---

stetho/src/main/java/com/facebook/stetho/inspector/elements/ShadowDocument.java

Full write-up "autopsy" coming soon, but wanted to get this up for review before that.
Closes #330

Fix NPE that happens during ShadowDocument.getGarbageElements()

---

README.md

The same will need to be applied to the website.

Tweak README to clarify stetho-okhttp3 dependency.

---

stetho/src/main/java/com/facebook/stetho/inspector/elements/Document.java

When an element is reparented, we must transmit the removal event before the insertion event. Otherwise the removal event gets ignored because the parent doesn't match up.
Closes #333

Fix for incoherent tree diffing

---

stetho/src/main/java/com/facebook/stetho/json/ObjectMapper.java

Caching this results in significant performance wins for the Elements tab, and probably for any other JSON serialization we're doing that uses enums with `@JsonValue `.
On a Moto E, I saw `Document.updateTree()` times drop from ~600ms to ~150ms in a scrolling ListView container.
I also experimented with a general reflection cache, e.g. Class<?>.getFields(), getEnumConstants(), etc. While that also seemed to improve things, it wasn't enough to inspire confidence just yet. I'll want to employ a micro-benchmark and/or sampling profiler before heading in that direction further.

Cache the result from ObjectMapper.getJsonValueMethod()

---

stetho/src/main/java/com/facebook/stetho/inspector/elements/android/ViewDescriptor.java

Remove static fields from exported properties

---

stetho/src/main/java/com/facebook/stetho/Stetho.java
stetho/src/main/java/com/facebook/stetho/inspector/database/DatabaseConnectionProvider.java
stetho/src/main/java/com/facebook/stetho/inspector/database/DefaultDatabaseConnectionProvider.java
stetho/src/main/java/com/facebook/stetho/inspector/database/DefaultDatabaseFilesProvider.java
stetho/src/main/java/com/facebook/stetho/inspector/database/SqliteDatabaseDriver.java

Manually merges #366 with API changes to better fit with #367.

Manual merge for DatabaseConnectionProvider API

---

stetho/src/main/java/com/facebook/stetho/inspector/elements/android/ViewDescriptor.java

Adds methods to get styles from Boolean, Short, Long, Double, Byte, and CharSequence.  Along with the existing methods for Float, Int, and Object, this should cover all of the View methods and fields with ViewDebug annotations so that all properties are shown in the Styles tab of the Elements panel.
Screenshot showing new properties:

Added methods to get styles from other data types

---

stetho-timber/build.gradle
stetho-timber/src/main/AndroidManifest.xml

This old Timber version causes me many troubles,
so please merge this new version fix

update timber version

---

README.md

Add details on OkHttp integration

---

build.gradle

Android Studio is very persistent about nagging about this.

Update to gradle 2.2.2

---

stetho/src/main/java/com/facebook/stetho/json/ObjectMapper.java

We should not be setting static fields from JSON data, or serializing them into JSON data. This prevents Stetho from working with Android Studio's Instant Run since it injects some stuff into there. This can manifest itself as a blank Elements tab, as well as no incoming data on any of the other tabs.

Fix ObjectMapper's treatment of static fields

---

stetho/src/main/java/com/facebook/stetho/inspector/elements/Document.java

Related to commit 37e615ed293ab49073f57b37e51fdcc6334cf919

Fix extranneous boxing and also fix use of binarySearch

---

stetho/src/main/java/com/facebook/stetho/inspector/elements/android/HighlightableDescriptor.java

Enable custom descriptors to be Highlightable

Make HighlightableDescriptor public

---

stetho/src/main/java/com/facebook/stetho/inspector/protocol/module/DOM.java

https://github.com/facebook/stetho/blob/master/build-tools/protocol.json#L2644

Fix typo for DOM.attributeModified

---

stetho-okhttp/src/main/java/com/facebook/stetho/okhttp/StethoInterceptor.java
stetho-okhttp3/src/main/java/com/facebook/stetho/okhttp3/StethoInterceptor.java
stetho-urlconnection/src/main/java/com/facebook/stetho/urlconnection/StethoURLConnectionManagerImpl.java
stetho/src/main/java/com/facebook/stetho/inspector/network/NetworkEventReporter.java
stetho/src/main/java/com/facebook/stetho/inspector/network/NetworkEventReporterImpl.java

	Introduce nextRequestId() method to ensure its uniqueness

---

build-tools/scraper.js

This PR adds events (instead of just commands) support for scraper.js
and fixes a crash when a type definition has no fields.

Expand scraper.js support for events.

---

stetho-js-rhino/README.md

This trailing parenthesis is a syntax error.

Remove extra parenthesis.

---

.travis.yml
build.gradle
gradle/wrapper/gradle-wrapper.properties
stetho-js-rhino/build.gradle
stetho-okhttp/build.gradle
stetho-okhttp3/build.gradle
stetho-sample/build.gradle
stetho-timber/build.gradle
stetho-urlconnection/build.gradle
stetho/build.gradle
stetho/src/main/java/com/facebook/stetho/inspector/elements/android/ViewHighlightOverlays.java

Fix for https://github.com/facebook/stetho/issues/607
https://github.com/facebook/stetho/commit/8874c9ff0b593d5530ffac5fd499a8147356e7cf
@jasta @aadsm

Fix #607: Stetho view inspection crashing apps on Android P DP4

---

.travis.yml

Using recommended workaround from: https://github.com/travis-ci/travis-ci/issues/8874

Fix travis CI issue with SDK manager and license acceptance

---

_layouts/home.html
_sass/_base.scss
index.md

Our mission at [Meta Open Source](https://opensource.facebook.com/) is to empower communities through open source, and we believe that it means building a welcoming and safe environment for all. As a part of this work, we are adding this banner in support for Ukraine during this crisis.

docs: add GH button in support of Ukraine
