- stetho/build.gradle
Release fail.  The stetho-1.0.0.jar that was released excludes
commons-cli and will fail as a result.  This dependency is so esoteric
for an Android app that it feels appropriate to just bundle it.
> Add fatjarRelease task to fix stetho.jar export

- README.md
Following up from discussion in #25, this updates the readme to precisely refer to the Chrome DevTools frontend UI.
> readme: Update usage of inspector & devtools

- .travis.yml
These artifacts are those downloaded as part of the dynamic build
process and which don't change regularly.
> Optimize Travis-CI builds by caching Gradle/Maven artifacts

- stetho/src/main/java/com/facebook/stetho/server/LocalSocketHttpServer.java
This caused all invocations to print a stack trace indicating a serious
sounding error when in fact everything was working fine.  Added a log
statement to clarify that everything is fine :)
Closes #49
> Break the bindToSocket retry loop on success

- .travis.yml
This just doesn't optimize things with Gradle due to the lock file being
changed in ~/.gradle/caches on each build.  Disable for now; hopefully
Travis-CI will fix this.
> Stop using Travis-CI cache

- stetho/src/main/java/com/facebook/stetho/common/Util.java
- stetho/src/main/java/com/facebook/stetho/server/LocalSocketHttpServer.java
Make bindToSocket static, mark it non-null and instead throw on error,
and clarify the "retry" semantic to actually indicate the number of
retries not number of tries.
> Minor fixes to bindToSocket

- stetho/src/main/java/com/facebook/stetho/inspector/network/NetworkEventReporterImpl.java
DevTools refuses to show any entry that lacks the `type` property in
recent versions.  This makes it possible to inspect network responses
that for whatever reason don't have the `Content-Type` header available.
Closes #57
> Avoid sending a null `type` or `mimeType` in network responses

- scripts/stetho_open.py
- stetho/src/main/java/com/facebook/stetho/server/LocalSocketHttpServer.java
Previously we formatted the process name using underscores due to
primitive tooling that has since been replaced.  We can now use the real
process name which fixes an issue with ./scripts/dumpapp output when
there are multiple targets that include derivative processes
(com.mypackage:myprocess).  Previously this would show up as
com.mypackage.myprocess.
> Use raw process name for UNIX abstract socket name

- stetho-okhttp/build.gradle
According to #59, it should be safe to just depend on 2.2.0 and ask the
dependency resolver to figure it out.
> Avoid wildcard dependency in stetho-okhttp

- release.gradle
- stetho/build.gradle
The fatjar release for 1.0.0 automatically merged commons-cli's
LICENSE.txt file into the base META-INF directory, appearing to replace
our own LICENSE with the Apache 2.0 license.  Very bad :)
This corrects the situation by somewhat manually organizing the
dependencies into the following structure:
META-INF/
META-INF/commons-cli-LICENSE.txt
META-INF/commons-cli-NOTICE.txt
META-INF/LICENSE
META-INF/MANIFEST.MF
META-INF/maven/
META-INF/maven/commons-cli/
META-INF/maven/commons-cli/commons-cli/
META-INF/maven/commons-cli/commons-cli/pom.properties
META-INF/maven/commons-cli/commons-cli/pom.xml
> Fix confusing LICENSE issue in fatjar release

- stetho/src/main/java/com/facebook/stetho/Stetho.java
- stetho/src/main/java/com/facebook/stetho/common/ExceptionUtil.java
- stetho/src/main/java/com/facebook/stetho/common/StringUtil.java
- stetho/src/main/java/com/facebook/stetho/common/Util.java
- stetho/src/main/java/com/facebook/stetho/common/android/ApplicationUtil.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/ChainedDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/DOMProvider.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/Descriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/DescriptorMap.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/NodeAttribute.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/NodeDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/NodeType.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/ObjectDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/ActivityDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/AndroidDOMProvider.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/AndroidDOMProviderFactory.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/ApplicationDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/TextViewDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/ViewDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/ViewGroupDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/ViewHighlighter.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/WindowDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/helper/ChromePeerManager.java
- stetho/src/main/java/com/facebook/stetho/inspector/helper/ObjectIdMapper.java
- stetho/src/main/java/com/facebook/stetho/inspector/protocol/module/DOM.java
This is a first stab at providing an Elements tab for Stetho.
The DOM class handles the JSON protocol and element <--> node ID mapping. An element is meant to be a real object in whatever DOM-type tree is being plugged in via a DOM.Provider implementation. We implement this in UIDOMProvider and our "DOM-type tree" is an Android application. We use the android.app.Application as the root of the DOM, its children are the android.app.Activity instances (initial list retrieved via a hack, then updated via Application.ActivityLifecycleCallbacks), then the android.view.Window and finally its android.view.View tree.
We use DOM.NodeDescriptor to describe an element in terms of a node (DOM.Node). In UIDOMProvider we use the element's class to figure out which descriptor(s) to use, but another …
> Initial check-in for Elements tab

- stetho/src/main/java/com/facebook/stetho/inspector/elements/AttributeAccumulator.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/ChainedDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/NodeDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/ObjectDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/TextViewDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/ViewDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/protocol/module/DOM.java
The 'id' attribute will now show up in a way that's recognizable from XML layouts, e.g. `id="@id/ima_button"`
I also refactored the protocol for retrieving attributes via NodeDescriptor to reduce allocations and CPU usage. I found that I was having to determine the contents of the attributes twice, once for getAttributeCount() to determine its existence, and then a second time in copyAttributeAt(). Since we currently only need to retrieve all the attributes at once, it makes sense to switch to an accumulator which can pack the name/value pairs directly into the interleaved String array that the JSON protocol uses. And the code is a lot simpler.
Closes #86
> Adding id attribute to Views

- stetho/src/main/java/com/facebook/stetho/Stetho.java
- stetho/src/main/java/com/facebook/stetho/inspector/database/DatabaseFilesProvider.java
- stetho/src/main/java/com/facebook/stetho/inspector/database/DatabasePeerManager.java
- stetho/src/main/java/com/facebook/stetho/inspector/database/DefaultDatabaseFilesProvider.java
- stetho/src/main/java/com/facebook/stetho/inspector/protocol/module/Database.java
- stetho/src/test/java/com/facebook/stetho/inspector/database/DatabasePeerManagerTest.java
Created an interface to provide database files at the time of a peer connection. This allows applications that create databases in directories other than the default one to have their data viewable in the Database section.
> Added a way to provide the database files to the DatabasePeerManager module.

- stetho/src/main/java/com/facebook/stetho/Stetho.java
- stetho/src/main/java/com/facebook/stetho/inspector/database/DatabasePeerManager.java
- stetho/src/main/java/com/facebook/stetho/inspector/protocol/module/Database.java
- stetho/src/main/java/com/facebook/stetho/inspector/protocol/module/DatabaseConstants.java
This solves #82. We use the prefix of the first 3 characters to determine what type of request it is. Since we only have access to "columns" and "error" text use the column to display the type and the value to display the count.
> support sending back rows changed

- stetho/src/main/java/com/facebook/stetho/inspector/ChromeDevtoolsServer.java
- stetho/src/main/java/com/facebook/stetho/inspector/network/NetworkEventReporterImpl.java
- stetho/src/main/java/com/facebook/stetho/inspector/protocol/module/Network.java
This solves #88.
@jasta that should do (solution 1), right?
> Catch out of memory exceptions while inspecting download of large files

- stetho/src/main/java/com/facebook/stetho/common/ReflectionUtil.java
- stetho/src/main/java/com/facebook/stetho/common/android/ApplicationUtil.java
- stetho/src/main/java/com/facebook/stetho/common/android/FragmentAccessor.java
- stetho/src/main/java/com/facebook/stetho/common/android/FragmentActivityAccessor.java
- stetho/src/main/java/com/facebook/stetho/common/android/FragmentApi.java
- stetho/src/main/java/com/facebook/stetho/common/android/FragmentApiUtil.java
- stetho/src/main/java/com/facebook/stetho/common/android/FragmentManagerAccessor.java
- stetho/src/main/java/com/facebook/stetho/common/android/ViewGroupUtil.java
- stetho/src/main/java/com/facebook/stetho/common/android/ViewUtil.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/ChainedDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/DOMProvider.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/Descriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/DescriptorMap.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/ActivityDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/AndroidDOMProvider.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/AndroidDescriptorHost.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/ApplicationDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/FragmentDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/HighlightableDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/TextViewDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/ViewDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/ViewGroupDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/ViewHighlighter.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/WindowDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/protocol/module/DOM.java
This adds support for Fragments in the element tree. Fragments will show up as the parent of the View that they contain, and therefore as the child of the ViewGroup which contains the Fragment's View. 
`ViewGroup -> Fragment -> View`
ViewGroupDescriptor does the high-level work of substituting Fragments for Views, and maintains a cache for mapping from Views to Fragments. Looking up the Fragment for a View is a bit expensive since it requires searching through all of the Fragments (see `FragmentApiUtil.findViewForFragment()`).
Closes #97
> Support for Fragments as parents of their associated View

- stetho/src/main/java/com/facebook/stetho/common/android/FragmentApi.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/AndroidDOMProvider.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/AndroidDOMRoot.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/ApplicationDescriptor.java
The node that we emit from DOM.getDocument() does not show up in the elements tab (it's just the way it works). Right now we are using the Application for that, which prevents us from seeing any information about it. By emitting a faux-node whose only purpose is to emit the Application as its sole child, we can now see details about Application itself. Even just having the class name helps answer the ever important question of "where is the code for this?"
Closes #99
> Application element is now the root node in the UI

- stetho/src/main/java/com/facebook/stetho/server/LocalSocketHttpServerConnection.java
All communication between host and Stetho is done by a LocalSocket (a
UNIX abstract domain socket) which has a very heavy-handed
implementation of LocalSocketImpl#flush which polls/sleeps waiting for
the kernel buffer to become empty.  This behaviour in practice reduces
observed throughput of dumpapp (using either the buffered stdout or
stderr) to between 300 and 600KB/s despite adb being capable of ~5MB/s
on the same device.
This workaround involves blocking the final flush call to the socket
output stream.  This still drains the local Java buffer as originally
intended, but does not ask the kernel to drain its buffer (and block
doing so).  This kernel draining behaviour is entirely unnecessary for
our purposes and presumably for everyone else as it appears to be added
for some special …
> Workaround serious throughput issue in Stetho's HTTP server

- stetho/src/main/java/com/facebook/stetho/Stetho.java
- stetho/src/main/java/com/facebook/stetho/common/ExceptionUtil.java
- stetho/src/main/java/com/facebook/stetho/common/Util.java
- stetho/src/main/java/com/facebook/stetho/dumpapp/ArgsHelper.java
- stetho/src/main/java/com/facebook/stetho/dumpapp/plugins/CrashDumperPlugin.java
Powerful mechanism to simulate a variety of crash/kill scenarios common
on Android to verify that crash recovery / reporters are functioning
properly.  Especially useful as a way to simulate the low memory killer
which normally requires a separate script to first determine your app's
pid then invoke adb shell run-as <yourpackage> kill <yourpid>.
Example usage:
dumpapp crash throw
dumpapp crash kill
dumpapp crash kill USR1
dumpapp crash exit 0
> Add `dumpapp crash` plugin

- scripts/hprof_dump.sh
- stetho/src/main/java/com/facebook/stetho/Stetho.java
- stetho/src/main/java/com/facebook/stetho/dumpapp/plugins/HprofDumperPlugin.java
This adds a convenient mechanism to dump an HPROF file from a running
Android application.  A companion script (`./scripts/hprof_dump.sh`) is
included to automatically run hprov-conf to convert it to the standard
Java HPROF file format for use in tools like Eclipse's MemoryAnalyzer.
> Add `dumpapp hprof` plugin

- scripts/dumpapp
- scripts/hprof_dump.sh
This allows a caller to respect the advice given by the error message
("Use -p to select a process...").  Also fix an issue where those error
messages would not be displayed correctly to the user by way of my
terrible misunderanding of Python3.
> Add `-p <process>` option to scripts/hprof_dump.sh

- stetho/src/main/java/com/facebook/stetho/inspector/network/NetworkEventReporterImpl.java
Unspecified in the protocol docs, we're expected to separate multiple
header values with the same name using a new line character.  This is
necessary because a normal JSON object cannot have the same name
repeated twice (and headers are encoded using a JSON object not an
array).
Closes #115
> Properly encode multiple headers with the same name

- stetho/src/main/java/com/facebook/stetho/common/Predicate.java
- stetho/src/main/java/com/facebook/stetho/common/android/ViewUtil.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/DOMProvider.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/AndroidDOMProvider.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/DOMHiddenView.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/ViewGroupDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/WindowDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/protocol/module/DOM.java
This allows the "inspector" magnifying glass to work on the elements tab. When you click on the button, it enters a modal state where you can pick which UI element should be highlighted. When you push your finger down on the Android app, it will hit-test and highlight the appropriate view on the device (and also as you move your finger around, if you'd like). When you move your finger up, a command will be sent back to Chrome and it will now highlight the view in the inspector UI.
Closes #124
> Inspector button on Elements tab

- stetho/src/main/java/com/facebook/stetho/Stetho.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/AndroidDOMConstants.java
The DOM module effectively doesn't work due to our hack that lists all
activities not functioning properly on previous versions of Android.
Without this, we currently cannot provide the DOM feature.
We can fix these issues by providing a manual API that informs us of
activity lifecycle events similar to Romain Guy's ViewServer:
https://github.com/romainguy/ViewServer
> Avoid installing the DOM module when Activity detection is unavailable

- stetho/src/main/java/com/facebook/stetho/common/android/HandlerUtil.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/DOMProvider.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/AndroidDOMProvider.java
- stetho/src/main/java/com/facebook/stetho/inspector/protocol/module/DOM.java
This patches DOM so that it calls into AndroidDOMProvider on the UI thread in the necessary locations. Otherwise we have a strong chance of stepping on UI objects from background threads. Proper enforcement and discovery of the threading model for AndroidDOMProvider needs a bit more chin-scratching, which we plan to do soon.
Closes #114
> DOM now calls into AndroidDOMProvider via the UI thread

- stetho/src/main/java/com/facebook/stetho/common/android/FragmentAccessor.java
- stetho/src/main/java/com/facebook/stetho/common/android/FragmentApi.java
- stetho/src/main/java/com/facebook/stetho/common/android/ResourcesUtil.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/FragmentDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/ViewDescriptor.java
Previously only View instances in the DOM would format ids using human
readable names.  This refactors the logic into a common class and
modifies FragmentDescriptor to support this.
> Bring id pretty printing to <fragment> support as well.

- stetho/src/main/java/com/facebook/stetho/common/android/ResourcesUtil.java
We thought we didn't need to check Resources against null, but we were sadly mistaken.
Closes #131
> Fix NPE crash in ResourcesUtil.getIdString()

- stetho/src/main/java/com/facebook/stetho/common/android/ViewUtil.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/AndroidDOMProvider.java
ViewUtil.hitTest() is now renamed to hitTestTouch() to better articulate what it should be used for.
We were having trouble in some apps where the inspector button wouldn't work very well: it would often latch onto layout containers that were empty overlay stubs. Since we can't actually send a touch event down and see how finally responds to it, we're adjusting our algorithm: ViewGroups are effectively a lower priority than regular Views. To implement this, we just do two passes of hit-testing: in the first pass, we don't allow a ViewGroup to be the result and instead return null. The second pass allows ViewGroups as a result.
Closes #133
> Improve Inspector button's hit-testing

- stetho/src/main/java/com/facebook/stetho/common/android/ViewUtil.java
VewUtil.hitTestImpl needs to recursively call itself, not hitTest(). Otherwise it defeats our heuristic, preventing allowViewGroupResult from being passed down the call chain.
Closes #142
> Fixed the implementation of ViewUtil.hitTestImpl()

- README.md
Eventually this will all be moved to a wiki page dedicated to dumpapp.
> Moved "Custom dumpapp plugins" to another section in README

- stetho-sample/src/debug/java/com/facebook/stetho/sample/APODDumperPlugin.java
- stetho-sample/src/debug/java/com/facebook/stetho/sample/SampleDebugApplication.java
- stetho-sample/src/main/java/com/facebook/stetho/sample/APODContentProvider.java
This adds a basic ContentProvider dumper for the APODContentProvider.
It supports clear/delete/list.
See https://gist.github.com/a351d105269845215c77 for sample output
It also fixes the APODContentProvider where it was not calling
notifyChange() on various write paths.
> Add APOD dumper

- stetho-sample/src/main/java/com/facebook/stetho/sample/APODActivity.java
- stetho-sample/src/main/java/com/facebook/stetho/sample/APODContentProvider.java
- stetho-sample/src/main/java/com/facebook/stetho/sample/APODContract.java
- stetho-sample/src/main/java/com/facebook/stetho/sample/APODRssFetcher.java
- stetho-sample/src/main/java/com/facebook/stetho/sample/HtmlScraper.java
- stetho/src/main/java/com/facebook/stetho/common/Utf8Charset.java
- stetho/src/main/java/com/facebook/stetho/common/Util.java
This adds somewhat arbitrary network overhead to highlight the kinds of
bugs/inefficiencies that Stetho is good at rooting out.  Specifically in
this case, we improved the quality of the APOD thumbnail image but by
greatly overfetching data and slowing down the UI.  Stetho's Network tab
makes it very easy to see why (adding an extra round-trip through an
HTML page and downloading images that are 4x+ larger than the space they
occupy)
> Fetch deep links to find large format image URLs for APOD sample

- stetho/src/main/java/com/facebook/stetho/inspector/domstorage/DOMStoragePeerManager.java
This is a simple race condition that was overlooked during development
and manifests itself in practice via a third party analytics library
(though it is not known which one exactly).  The issue is clearly
demonstrable outside the context of this library though.
Closes #151
> Fix crash when rapidly adding/removing SharedPreferences keys

- stetho/src/main/java/com/facebook/stetho/inspector/database/DatabasePeerManager.java
when enabling WAL for SQLite the files used for journaling change.
See: https://www.sqlite.org/wal.html
> ignore meta-data for SQLite using WAL

- stetho/src/main/java/com/facebook/stetho/common/ThreadBound.java
- stetho/src/main/java/com/facebook/stetho/common/UncheckedCallable.java
- stetho/src/main/java/com/facebook/stetho/common/android/HandlerUtil.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/ChainedDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/DOMProvider.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/Descriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/NodeDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/ActivityDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/AndroidDOMProvider.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/ViewHighlighter.java
- stetho/src/main/java/com/facebook/stetho/inspector/protocol/module/DOM.java
This introduces a new interface, ThreadBound, which provides methods for dealing with the UI thread safety contract that we need to enforce w.r.t. Android UI objects. We are also much more stringent about verifying that calls are being made on the correct thread.
Closes #167
> Clarify and enforce thread safety contract of DOMProvider et. al.

- stetho/src/main/java/com/facebook/stetho/inspector/console/RuntimeRepl.java
- stetho/src/main/java/com/facebook/stetho/inspector/console/RuntimeReplFactory.java
- stetho/src/main/java/com/facebook/stetho/inspector/protocol/module/Runtime.java
This allows third parties to provide their own REPL implementation to
interpret commands from the Console.  Eventually we'd like to explore
possibly using bsh or some other Java evaluation framework that is
enabled if detected in the classpath.  This is the first small step in
that direction.
Tested that exception processing and arbitrary object return types do
indeed work.
> Introduce plugin framework for Console tab evaluation support

- stetho/src/main/java/com/facebook/stetho/common/android/FragmentCompat.java
- stetho/src/main/java/com/facebook/stetho/common/android/FragmentCompatFramework.java
- stetho/src/main/java/com/facebook/stetho/common/android/FragmentCompatSupportLib.java
- stetho/src/main/java/com/facebook/stetho/common/android/FragmentCompatUtil.java
This is done by simply checking whether we have an instance of
FragmentActivity before taking the support library path.  The framework
path doesn't need this check since it's impossible that if we have an
Activity and we are on a sufficiently high API level that the Activity
doesn't have fragment support.
Closes #176
> Fix crash when the support library is present but not used for a particular Activity

- stetho/src/main/java/com/facebook/stetho/common/android/FragmentCompat.java
- stetho/src/main/java/com/facebook/stetho/common/android/FragmentCompatFramework.java
- stetho/src/main/java/com/facebook/stetho/common/android/FragmentCompatSupportLib.java
This one is deceptively fragile because FragmentManager is an abstract class and we actually need to pull mAdded from the derived class FragmentManagerImpl.
Closes #182
> Fix Fragment support in Elements tab

- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/ViewHighlightOverlays.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/ViewHighlighter.java
This is how it looks like after I set the button margins and paddings to 10dp each
Ideally the margins should be drawn outside the view bounds so that it doesn't overlap with the padding, but I couldn't find a simple way to do it for now. Any ideas?
> Adds padding/margin highlights

- stetho/src/main/java/com/facebook/stetho/common/Util.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/ChainedDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/DOMProvider.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/Descriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/NodeDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/ObjectDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/AndroidDOMProvider.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/MethodInvoker.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/ViewDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/protocol/module/DOM.java
- stetho/src/test/java/com/facebook/stetho/inspector/elements/android/MethodInvokerTest.java
- stetho/src/test/java/com/facebook/stetho/inspector/elements/android/ViewDescriptorTest.java
Fixes #145 
This is my initial stab at implementing a new DOM request `setAttributesAsText()`.
Right now this correctly calls any setter that has a single argument of type `int`, `float`, `boolean`, `String` or `CharSequence` of `View` (and subclasses) using the `MethodInvoker`. 
Examples are `setTex()t`, `setId()`, `setAlpha()`, etc. More types can be supported by extending `TypedMethodInvoker`.
Question: 
* Do we need to send a response back after completed?
> Implements support for DOM.setAttributesAsText()

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- stetho-okhttp/build.gradle
- stetho/build.gradle
First party unit testing support is available in the android gradle build tools since version 1.1.0 ([more info](http://tools.android.com/tech-docs/new-build-system)).
This means we don't need to use a custom test plugin and can use the latest gradle build tools, which was incompatiple with the `android-unit-test` plugin.
With this, we get syntax highlighting and autocompletion support for the tests in Android Studio, which was also not available before version 1.1.0
> Use first-party test support in gradle plugin

- stetho/src/main/java/com/facebook/stetho/common/Accumulator.java
- stetho/src/main/java/com/facebook/stetho/common/ArrayListAccumulator.java
- stetho/src/main/java/com/facebook/stetho/common/ListUtil.java
- stetho/src/main/java/com/facebook/stetho/common/ThreadBound.java
- stetho/src/main/java/com/facebook/stetho/common/android/ViewGroupUtil.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/ChainedDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/DOMProvider.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/DOMView.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/Descriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/ElementInfo.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/NodeDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/ObjectDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/ShadowDOM.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/ActivityDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/AndroidDOMProvider.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/AndroidDOMRoot.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/ApplicationDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/FragmentDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/TextViewDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/ViewDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/ViewGroupDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/WindowDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/helper/ChromePeerManager.java
- stetho/src/main/java/com/facebook/stetho/inspector/jsonrpc/JsonRpcPeer.java
- stetho/src/main/java/com/facebook/stetho/inspector/protocol/module/DOM.java
The original problem is that ListView updates just didn't work: the ordering was all wrong after scrolling around because we didn't get any updates from ViewGroup.OnHierarchyChangedListener. 
We've known for awhile that we need to have some kind of support for DOM tree diffing because every location in the Android UI tree seems to require a different protocol for subscribing to change notifications (if it's even possible), some of which have require brittle, reflection-based hacks (yuck). 
DOM tree diffing necessitates the use of a "shadow DOM" which contains a copy of the DOM so can keep track of what we've sent to Chrome and compare it to what the DOMProvider says the tree should look like now.
DOM tree diffing is split into 3 phases:
* Collecting changes to the shadow DOM. We currently …
> Implementation of DOM tree diffing (fixes ListView, et. al.)

- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/ViewGroupDescriptor.java
This switches ViewGroupDescriptor to using a WeakHashMap for the View -> [View or Element] cache.
I also moved this cache out of ViewGroupDescriptor.ElementContext and into ViewGroupDescriptor because we don't really need to cache this per-ViewGroup. Why not save a few allocations per ViewGroup?
Closes #203
> Fix memory leak in ViewGroupDescriptor

- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/ViewGroupDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/WindowDescriptor.java
Marking a `ViewGroup` as a `decorView` was a necessary optimization due to the old `getChildCount` + `getChildAt` protocol. Now that we've transitioned to `getChildren(Accumulator)`, we don't need to do linear scans in order to answer those questions. Technically, the linear scan adds up to a quadratic scan for decor views, but they only have 1 child so that didn't matter. It did make the code a bit nasty.
And since we don't need the decor view marking anymore, and since the `View` --> `Element` cache was moved out of `ViewGroupDescriptor.ElementContext` into `ViewGroupDescriptor` ( #206 ), that means we can just delete `ViewGroupDescriptor.ElementContext`. This saves 1 allocation per `ViewGroup`. Hoo-ray :)
Closes #205
> Improve ViewGroupDescriptor by removing unnecessary stuff

- stetho/src/main/java/com/facebook/stetho/common/android/DialogFragmentAccessor.java
- stetho/src/main/java/com/facebook/stetho/common/android/FragmentAccessor.java
- stetho/src/main/java/com/facebook/stetho/common/android/FragmentCompat.java
- stetho/src/main/java/com/facebook/stetho/common/android/FragmentCompatFramework.java
- stetho/src/main/java/com/facebook/stetho/common/android/FragmentCompatSupportLib.java
- stetho/src/main/java/com/facebook/stetho/common/android/FragmentCompatUtil.java
- stetho/src/main/java/com/facebook/stetho/common/android/ViewUtil.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/AbstractChainedDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/ChainedDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/Descriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/DescriptorMap.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/ActivityDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/AndroidDOMProvider.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/AndroidDOMRoot.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/ApplicationDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/DialogDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/DialogFragmentDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/FragmentDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/TextViewDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/ViewDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/ViewGroupDescriptor.java
This adds support for `DialogFragment`s in the Elements tab. This code is actually pretty straightforward now that tree diffing is checked in ( #204 ), without which I had code with all sorts of clowney timers and stuff.
I refactored `ChainedDescriptor` to be an interface, with `AbstractChainedDescriptor` sitting on top of it as the canonical implementation. I did this because `DialogFragmentDescriptor` has the unique problem of needing to *not* pass-through to its super-descriptor's implementation of `getChildren()`. If it did, then it would emit both the `View` and the `Window` which contains the `View`. Not only would this be silly, but it causes an infinite loop and would break all sorts of stuff that assume each element can only appear once in the DOM tree. I chose this approach …
> Implementation of DialogFragment support for Elements

- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/AndroidDOMProvider.java
- stetho/src/main/java/com/facebook/stetho/inspector/protocol/module/DOM.java
`AndroidDOMProvider` was always trying to push updates over to `DOM`, but `DOM` hadn't created its `mShadowDOM` yet. Woops.
This NPE actually found a performance issue: even if the Elements tab isn't clicked on, we were still running our diffing workflow which rescans the whole UI tree every second. We shouldn't be running this code until you click on the Elements tab, which causes the first `DOM.getDocument()` call, which is a much better time to boot that up.
Closes #215
> Fix crash in Elements when it's not the startup tab

- stetho/src/main/java/com/facebook/stetho/inspector/database/DatabasePeerManager.java
PRAGMA requires query/rawQuery to work and yields an error when we were
using execSQL anyway.  This simple change makes it possible to use
PRAGMA to yield results.
Closes #214
> Support PRAGMA statements explicitly

- stetho/src/main/java/com/facebook/stetho/inspector/database/DatabasePeerManager.java
Hello,
I noticed that `EXPLAIN` queries run via the Web SQL console were failing with the error: *Queries can be performed using SQLiteDatabase query or rawQuery methods only.*
I tried to add `EXPLAIN` support by going through the path for `SELECT`, and sure enough, I got back a usable result.
> Add support for EXPLAIN queries run via Web SQL console.

- gradle.properties
This was supposed to be done after 1.1.1 was cut but I must have forgot.
Sigh, we need to bring in the gradle release plugin :)
> Change version to 1.2.0-SNAPSHOT

- stetho-okhttp/src/main/java/com/facebook/stetho/okhttp/StethoInterceptor.java
- stetho-okhttp/src/test/java/com/facebook/stetho/okhttp/StethoInterceptorTest.java
- stetho-urlconnection/src/main/java/com/facebook/stetho/urlconnection/StethoURLConnectionManagerImpl.java
- stetho-urlconnection/src/main/java/com/facebook/stetho/urlconnection/URLConnectionInspectorRequest.java
- stetho/src/main/java/com/facebook/stetho/inspector/network/DecompressionHelper.java
- stetho/src/main/java/com/facebook/stetho/inspector/network/RequestBodyHelper.java
Request decompression is not officially part of the standard but many
mobile implementations choose to do it because payloads tend to be quite
large on clients and servers these days are easily made to support it.
This diff simply makes it so that Stetho will show the decompressed
payload, but still report the compressed payloads size to the UI.
Note that this only affects stetho-urlconnection and stetho-okhttp.
Other modules must manually implement this as it is not possible given
the existing API contract to do it transparently.
Closes #111
> Implement transparent request decompression

- stetho/src/main/java/com/facebook/stetho/inspector/network/RequestBodyHelper.java
Following up from #111 and testing #248 
This was using the wrong class (Deflate is the compression, inflate is the reverse). `InflaterOutputStream` properly inflates the request body, and works for our project when I tested out the change.
CC @jasta
> Fix RequestBodyHelper body inflation

- stetho/src/main/java/com/facebook/stetho/inspector/network/AsyncPrettyPrinterInitializer.java
- stetho/src/main/java/com/facebook/stetho/inspector/network/NetworkEventReporterImpl.java
- stetho/src/main/java/com/facebook/stetho/inspector/network/NetworkPeerManager.java
- stetho/src/main/java/com/facebook/stetho/inspector/protocol/module/Network.java
- stetho/src/test/java/com/facebook/stetho/inspector/network/AsyncPrettyPrintResponseBodyTest.java
Right now, pretty printers are instantiated and registered at the start up path. This PR moves these steps to onFirstPeerRegistered() for NetworkPeerManager's listener.
> Fix registration flow for Async Pretty Printer

- stetho/src/main/java/com/facebook/stetho/inspector/network/DownloadingAsyncPrettyPrinterFactory.java
Right now, stetho attempts to download schema content with the url provided without checking status code. This PR adds the functionality of checking status code before passing the schema content to pretty printer.
> Add status code checking for schema download

- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/ActivityTracker.java
- stetho/src/main/java/com/facebook/stetho/inspector/protocol/module/Page.java
- stetho/src/main/java/com/facebook/stetho/inspector/screencast/ScreencastDispatcher.java
Tries to implement screencasting support as described in #189 
It is still a bit janky but works. I'll try to get it improved.
Still needs to be fixed:
* When the app is closed while the screencast is running, we get a crash since the bitmap is disposed and we never got a chance to set `mIsRunning` to false. Need to find a way to detect that the activity is closing, maybe `isFinishing()` would do.
* Jankiness
Nice to have:
* Touch support
> Screencasting support

- stetho-js-rhino/README.md
- stetho-js-rhino/src/main/java/com/facebook/stetho/rhino/JsRuntimeReplFactoryBuilder.java
- stetho/src/main/java/com/facebook/stetho/inspector/protocol/module/Runtime.java
- stetho/src/main/java/com/facebook/stetho/inspector/runtime/RhinoDetectingRuntimeReplFactory.java
This diff focuses on making stetho-js-rhino a bit more of a first-party
citizen in Stetho, with the default implementation both detecting it
more conveniently and automatically using it if available or
recommending users add it to the classpath so that it will be
autodetected.
> Autodetect stetho-js-rhino and use it

- release.gradle
Java 8 became much more strict about enforcement of HTML syntax and
rules which breaks the norms we were previously adhering too.
> Fix javadoc errors on Java 8

- stetho/src/main/java/com/facebook/stetho/Stetho.java
This was accidentally broken in #245 by not modifying the default
inspector modules provider to use the new Runtime(Context) constructor,
effectively disabling the entire feature.
> Fix the Rhino autodetection feature

- stetho/src/main/java/com/facebook/stetho/Stetho.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/Document.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/DocumentProvider.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/DocumentProviderFactory.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/DocumentProviderListener.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/AndroidDocumentProvider.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/AndroidDocumentProviderFactory.java
- stetho/src/main/java/com/facebook/stetho/inspector/protocol/module/Runtime.java
As the DevTools implementation has matured it has become clear that the
modules are not truly modular or interchangable at all and have heavy
dependencies between the two that make it impossible to provide or
configure them in isolation.  Because of this, we're moving to a more
explicit customization API which is responsible for managing the
dependencies of the implementation directly while still preserving the
level of abstractions already present in the system (such as providing a
custom document model, runtime REPL, etc).
> Further refine DefaultInspectorModulesBuilder

- stetho-js-rhino/README.md
The snippet shows how to plug the InspectorModulesProvider with stetho's
WebKit inspector.
I think that this documentation snippet is more complete.
> Update stetho-js-rhino's README with a more complete config snippet

- stetho/src/main/java/com/facebook/stetho/Stetho.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/AbstractChainedDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/Document.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/ShadowDocument.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/AndroidDocumentConstants.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/AndroidDocumentProvider.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/DocumentHiddenView.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/ViewGroupDescriptor.java
We renamed `DOMProvider` to `DocumentProvider` while doing the refactor to extract `Document` out of `DOM`. There were a few places we missed. We also need to use some different terminology within `Document`: instead of saying things like "transmit to the DOM" we need to say "transmit to our listener." In some places it's fine to refer to DOM because it's a reference to the realities of the concrete protocol we're using.
Closes #273
> Finish renaming DOM to Document where appropriate

- stetho/src/main/java/com/facebook/stetho/Stetho.java
- stetho/src/main/java/com/facebook/stetho/common/ListUtil.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/AbstractChainedDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/Document.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/NodeDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/ObjectDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/Origin.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/StyleAccumulator.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/DialogFragmentDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/ViewDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/helper/IntegerFormatter.java
- stetho/src/main/java/com/facebook/stetho/inspector/protocol/module/CSS.java
This pull request adds the ability to view the style of an element that is selected in the elements tree using the same UI as what is shown in the styles tab when inspecting an element of a webpage.
Some gotchas:
* The names of style properties shown are not copied verbatim from the names of fields in the `View` class, but are translated to a format that Chrome understands. For example, `View` has a field called `paddingLeft`, but in order for that to be rendered correctly in Chrome, it needs to be transmitted as `padding-left`. 
* Default values are not transmitted, unless they are of an enum type, in which case they are *always* transmitted.
* Due to inconsistencies between annotations present on certain Android SDK versions, some fields that are enums are not translated into their …
> Added the ability to inspect an element's style

- stetho/src/main/java/com/facebook/stetho/inspector/database/DatabasePeerManager.java
Simple change to make views (as with CREATE VIEW ...) show up in the
WebSQL section as a table.  Quick smoke test reveals there's no trouble
treating them as tables in Stetho.
Closes #285
> Show SQLite views as tables

- scripts/dumpapp
- scripts/stetho_open.py
We want to be able to support passing the process via environment
variable. This gets around having to create arbitrary wrapper scripts
that just pass `-p myprocess $@` to dumpapp.
Closes #291 
https://gist.github.com/anonymous/b20a4e34cf774b4abdb6
> Add support for STETHO_PROCESS environment variable to dumpapp

- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/ViewDescriptor.java
Makes it much easier to read
Before:
After:
> Sort the View CSS properties by cssName

- stetho/src/main/java/com/facebook/stetho/json/ObjectMapper.java
This branch fixes serialization issues that cause stetho to die when we try to send back NaN, Infinity or -Infinity. These values are not part of the JSON specification. What this patch does is to serialize them as String since JavaScript will accept them back as Doubles.
> Json serialization fixes

- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/ViewGroupDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/ViewHighlighter.java
1. The map in ViewGroupDescriptor now stores WeakReference<Object> as a value instead of Object directly. Since views were stored there directly that could cause activities to be leaked through the context of the view.
2. The highlight view field is now nulled out when the highlighting is cleared.
> Fixed a couple of memory leaks.

- stetho-js-rhino/build.gradle
- stetho-js-rhino/proguard-consumer.pro
- stetho/build.gradle
- stetho/proguard-consumer.pro
v0.5.7 of the android gradle build plugin added support for bundling proguard rules in an aar using `consumerProguardFiles`
This adds base proguard rules to the stetho aar and stetho-js-rhino aar. This will allow usage of these modules in a proguarded project without the developer needing to hunt down and configure proguard for stetho.
> Bundle default proguard rules

- stetho-timber/src/main/java/com/facebook/stetho/timber/StethoTree.java
`ASSERT` log level often means **never_should_happen** type of errors, so let them look like errors in Chrome console.
> Display logs with ASSERT level as ERROR messages in Chrome console.

- stetho-js-rhino/build.gradle
- stetho-js-rhino/src/test/java/com/facebook/stetho/rhino/JsFormatTest.java
Turns out that in the pull request "Js tweaks #286" it was mentioned that
the unit tests where using Robolectric for no reason.
Somehow the patch with the unit tests fix wasn't merged.
> Unit tests for stetho-js-rhino are now using jUnit4 (ditching Robolectric)

- stetho/src/main/java/com/facebook/stetho/inspector/protocol/module/Database.java
- stetho/src/test/java/com/facebook/stetho/json/ObjectMapperTest.java
DevTools appears to have problems accepting values near
Long.MIN/MAX_VALUE as integer types despite JSONs explicit support for
this.  Since it appears not to care at all what JSON type is used, a
String substitution appears to nicely fix the issue with no observable
visual effects.
Fixes #310
> Work around DevTools issue formatting Long.MIN_VALUE

- scripts/stetho_open.py
This is a cleanup diff to fix an issue accidentally left in
eb0ca3d565ce75f147d3ef8d376230f4e1f263a2.  Since we landed on just
having one socket, we don't need to support the extra *_dumpapp socket
name and in fact this script did so in a way that broke the -p use case.
> No longer search for _dumpapp socket names

- stetho/src/main/java/com/facebook/stetho/inspector/protocol/module/DOM.java
- stetho/src/test/java/com/facebook/stetho/json/ObjectMapperTest.java
Looks like this actually broke back in #237. We missed 1 tiny detail in the middle of a very large refactoring job.
When we transmit DOM changes to Chrome, we need to keep track of all the elements for each transmission so we don't send over duplicates. When we send over `DOM.childNodeInserted(E)`, which includes E and its whole sub-tree "by value", we must not send a subsequent `DOM.childNodeInserted(*)` for any elements within E's sub-tree, otherwise they'll show up as duplicates in the DevTools UI.
This was managed with a `HashSet` indirectly populated by `DOM.createNodeForElement()` and checked by `ShadowDocument.applyDocumentUpdate()`. The code is still there in the latter, but it got lost in the former. It was only storing the root node of any transmitted sub-tree into the `HashSet` …
> Fix for duplicates in Element tree, and fix JSON unit test

- scripts/dumpapp
- scripts/stetho_open.py
- Reading from socket in stetho_open was not correctly maintaining the number of bytes to read
- Reading from socket in dumper script must be done in a loop until the expected number of bytes is received
- Writing to stdout should be followed by a flush, so data is displayed as soon as it's received
> A couple of script fixes

- stetho/src/main/java/com/facebook/stetho/dumpapp/ArgsHelper.java
This can come handy, especially when working with libraries that require an array of string to parse commands, such as Commons CLI's CommandLineParser.
> Added a utility method to convert args iterator to array of args.

- stetho/src/main/java/com/facebook/stetho/inspector/database/SqliteDatabaseDriver.java
When opening a table the DatabaseFilesProvider is first checked for the table then if not found there we fall back to the context.getDatabasePath() call.
If a custom DatabaseFilesProvider is used then the context.getDatabasePath() won't find those databases.
> Fixed SqliteDatabaseDriver with custom DatabaseFilesProvider

- stetho/src/main/java/com/facebook/stetho/Stetho.java
- stetho/src/main/java/com/facebook/stetho/inspector/database/DatabaseConnectionProvider.java
- stetho/src/main/java/com/facebook/stetho/inspector/database/DefaultDatabaseConnectionProvider.java
- stetho/src/main/java/com/facebook/stetho/inspector/database/SqliteDatabaseDriver.java
Allows users to work around #84 by providing their own Connection Provider that returns their active Database handle.
> Database connection provider

- stetho/src/main/java/com/facebook/stetho/inspector/database/DefaultDatabaseConnectionProvider.java
- stetho/src/main/java/com/facebook/stetho/inspector/database/SQLiteDatabaseCompat.java
This diff adds a WAL-guessing heuristic to support most database users
for the common case as well as expands upon
DefaultDatabaseConnectionProvider to fully support subclassing to
conveniently select custom options on a per database file basis.
> Improve support for custom SQLite open flags

- stetho/src/main/java/com/facebook/stetho/common/ListUtil.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/AbstractChainedDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/Document.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/NodeDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/ObjectDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/AccessibilityNodeInfoWrapper.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/DialogFragmentDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/ViewDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/protocol/module/CSS.java
Added the basic start for accessibility inspection, and a wrapper class to hold all of the methods for various accessibility properties I plan to add to the inspector.  For now these will appear as a second CSS Selector alongside other view properties.  The only one currently implemented is "ignored", which signifies whether or not a node will be ignored by accessibility services.
I plan to follow the properties of the AXNode type in the Chrome Debugging Protocol (http://chromedevtools.github.io/debugger-protocol-viewer/tot/Accessibility/#type-AXNode).  This will make it easier to transition to the Accessibility Panel if Stetho is upgraded past the 1.1 version of the protocol.
I'm not sure if this is a problem, but by adding the "getStyleFromBoolean" and getStyleFromCharString" methods …
> Accessibility

- stetho/src/main/java/com/facebook/stetho/common/android/AccessibilityUtil.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/AccessibilityNodeInfoWrapper.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/ViewDescriptor.java
Added ignored-reasons as a property to the Accessibility Properties panel, which explains in plain language why a node is being ignored by accessibility.
I've also updated the ignored property to be more accurate to what Talkback and other Accessibility Services actually look for to determine whether or not to ignore a view.
> Added ignoredReasons to accessibility inspection

- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/AccessibilityNodeInfoWrapper.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/ViewDescriptor.java
This adds "focusable", "focusable-reasons", "focused", "description", and "actions" to the Accessibility Properties.  I'll detail below what each of these mean:
**Focusable**
This is the inverse of "ignored", and simply states whether or not a view will be able to be focused by an `AccessibilityService`.
**Focusable Reasons**
Similar to ignored-reasons, this states precisely _why_ a view is focusable.  This will help people to understand how to make a view that they don't want to be focusable, not get focus.
**Focused**
This will be true for the currently accessibility-focused view, and false for all others.  This will help determine precisely which view is receiving focus at any given time, which can often be difficult to determine when you have a deep view hierarchy.
**Description** …
> Added various other properties to the accessibility inspection

- .travis.yml
- build.gradle
- stetho-js-rhino/build.gradle
- stetho-okhttp/build.gradle
- stetho-okhttp3/build.gradle
- stetho-sample/build.gradle
- stetho-timber/build.gradle
- stetho-urlconnection/build.gradle
- stetho/build.gradle
This updates the build tools to `24.0.1` and the Android Gradle plug-in to `2.1.3` (latest versions as of Aug 18, 2016)
> Update build tools and Android plug-in

- release.gradle
There have been a number of problems lately when it comes to how gradle is assembling the output to maven. Specifically the fact that the default packaging is a jar. This means no proguard files are included (See #419). There was a hack that you can do 
```
debugCompile ('com.facebook.stetho:stetho:1.3.1:@aar') {
transitive = true
}
```
this allows you to get a proguard file and does not compile the R.java files (See #422). 
In order to test this I ran 
`./gradlew installArchives` then modified the sample app's build.gradle to be 
```
...
dependencies {
...
compile 'com.facebook.stetho:stetho:1.3.2-SNAPSHOT'
....
}
repositories {
maven { url System.getenv('HOME') + "/.m2/repository/" }
}
```
I also modified the sample app to perform proguard minification `minifyEnabled true`, and was able …
> Remove creation of jars in output

- stetho/src/main/java/com/facebook/stetho/inspector/database/DefaultDatabaseFilesProvider.java
The API for `DatabaseProvider` is to return `List<File>` however the
current implementation of `DefaultDatabaseProvider` returns a `File`
that does not exist. We were able to get around this before due to the
fact that the file was only used to call `File#getName()`.
In #390 this was changed and the actual `File` object was used to open
the database.
This fixes #431
> Have DefaultDatabaseProvider return filename

- index.md
Make it clear that the two code samples relate to different versions of
OkHttp, and add a warning on the order of interceptors (see #423).
> Add details on OkHttp integration

- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/AccessibilityNodeInfoWrapper.java
ViewParents that contain both focusable, and unfocusable children were incorrectly having their description set to the concatenation of all children.  The parent should have only had its description contain the descriptions of the unfocusable children, since the focusable children will retain their own descriptions and focus.
> Make sure only unfocusable children's descriptions are being co-opted by parents

- stetho-okhttp3/build.gradle
We are using Stetho for debugging applications. It's very useful! We thank for this community.
Sometimes, we are suffering conflicts of dependencies by the Okhttp's version that included by Stetho.
We hope that Stetho uses latest version of Okhttp. Thank you.
> Update Okhttp3 to 3.4.2

- stetho/src/main/java/com/facebook/stetho/json/ObjectMapper.java
Fix NPE when an IllegalArgumentException is thrown from `field.set`.
fixes #447
> Fix NPE in ObjectMapper

- scripts/dumpapp
- scripts/stetho_open.py
This change now uses ANDROID_ADB_SERVER_PORT when connecting to adb, if
a numeric value is specified. Otherwise the default port (5037) is used.
> stetho_open.py should respect ANDROID_ADB_SERVER_PORT

- stetho/src/main/java/com/facebook/stetho/inspector/elements/AbstractChainedDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/ChainedDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/Descriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/NodeDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/ObjectDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/ActivityDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/DialogDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/DialogFragmentDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/FragmentDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/HighlightableDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/ViewDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/WindowDescriptor.java
Previously only AbstractChainedDescriptor was generic. Anyone extending
directly from Descriptor or implementing HighlightableDescriptor had to
make sure to add casts from Object to their concrete type. This diff
solves that by making all descriptors generic.
> Make NodeDescriptor, Descriptor, and HighlightableDescriptor generic

- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/ActivityDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/AndroidDescriptorHost.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/AndroidDocumentProvider.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/DialogDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/DialogFragmentDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/FragmentDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/HighlightableDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/ViewDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/ViewHighlightOverlays.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/ViewHighlighter.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/WindowDescriptor.java
A descriptor may not map directly to a View. For example if a
Descriptor was created for a Drawable it may occupy only a partial
space in the View. This diff solves this problem for descriptor
highlighting by extending HighlightableDescriptor with a method for
returning the bounds to highlight. Returning null will highlight the
full bounds of the View.
> Add ability to highlight sub-bounds of view

- stetho/src/main/java/com/facebook/stetho/Stetho.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/DescriptorMap.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/DescriptorProvider.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/DescriptorRegistrar.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/AndroidDocumentProvider.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/AndroidDocumentProviderFactory.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/DialogFragmentDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/FragmentDescriptor.java
This commit introduces the notion of a DescriptorProvider. A
DescriptorProvider is an object which given a DescriptorMap will
register a number of Descriptors. A list of DescriptorProviders can be
passed to the AndroidDocumentProviderFactory to add or override
descriptors for class of your choosing. This functionality enables
applications and libraries to add their own descriptors while relying
on Stetho defaults for all other settings.
> Add ability to register custom descriptors

- stetho/src/main/java/com/facebook/stetho/inspector/elements/AbstractChainedDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/ComputedStyleAccumulator.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/Document.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/NodeDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/ObjectDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/DialogFragmentDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/ViewDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/protocol/module/CSS.java
Currently two selector names are hard-coded in DOM.java.
"<this_element>" and "Accessibility Properties". With this commit
descriptors are able to themselves choose what the selector name should
be and how their various properties should be distributed among the
selectors.
This enables an element to have styles such as:
```
layout {
width: 100px;
height: 100px;
}
props {
text: "Hello World";
}
```
Due to this requiring an added property in StyleAccumulator I chose to
also take this commit to split up styles from computed styles which are
two separate concepts but up until now have been handled the same. A
style may be `width: 100%` while a computed style would be `width:
320px`.
> Move selector naming to the descriptor

- stetho-sample/src/main/java/com/facebook/stetho/sample/APODRssFetcher.java
The RssFetcher in the sample app talks to [http://apod.nasa.gov/apod.rss](url). Probably due to a configuration change at server recently, it returns 302 and app shows a blank list (doesn't handle redirection very well). Fix it by pointing to latest url.
> Fixes rss url; otherwise it gets 302 status code and shows a blank list.

- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/ViewHighlighter.java
The bounds passed to `setHighlightedViewImpl` is `@Nullable` but not the bounds declared in `HighlightOverlays.highlightView`. This commit makes sure `HighlightOverlays.highlightView` is always passed a non-null `Rect`.
> Use empty rect if bounds are null, avoiding NPE

- stetho/src/main/java/com/facebook/stetho/common/StringUtil.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/AbstractChainedDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/Document.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/NodeDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/ObjectDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/StyleRuleNameAccumulator.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/DialogFragmentDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/ViewDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/protocol/module/CSS.java
This commit adds support for editable style properties based on rule
name (previously called selector). Previously properties had to be
implemented as attributes to be able to be edited.
> Add support for editable style properties

- stetho/src/main/java/com/facebook/stetho/common/android/ViewUtil.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/ActivityDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/AndroidDescriptorHost.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/AndroidDocumentProvider.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/DialogDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/DialogFragmentDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/FragmentDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/HighlightableDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/ViewDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/ViewGroupDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/WindowDescriptor.java
With the ability to implement custom descriptors also came the ability to highlight non-view elements. However this feature was not extended to handle click inspection. This commit resolves that by generalizing some of the hit testing logic and moving it into highlightable descriptors.
In a follow up PR I will try to decouple most of the highlighting from android Views.
> Improve hit testing to handle non-view elements

- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/AndroidDocumentProvider.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/ViewGroupDescriptor.java
1. Tell chrome to inspect the clicked element, not the view which is
highlighted.
2. Find child to return back to front to respect z ordering.
3. Disregard hidden views and views which are not focusable.
> Some fixes to recent hit test improvements

- scripts/dumpapp
This PR corrects a larger signedness mismatch between dumpapp client and
server.  The dumpapp client (python) used unsigned integers where the
server (Android/Java) used signed integers due to a limitation in
DataInput/OutputStream not supporting unsigned 32 and 64-bit types
(technically this could be done with readLong & 0xffffffffff though).
The critical fix comes in when sys.stdin.buffer.read reaches EOF whereby
the client tried to pack -1 in an unsigned int which is not obviously
not possible.  Since the server was always expecting this to be signed, simply
correcting the client causes the problem to go away.
Closes #509
> Fix stdin issue when the stream is read to exhaustion.

- stetho-urlconnection/src/main/java/com/facebook/stetho/urlconnection/URLConnectionInspectorHeaders.java
URLConnection back by earlier versions of OkHttp (1.5.x) has all lowercased header names, this PR fixed empty Content-Type issue.
> Made URLConnectionInspectorHeaders case insensitive

- stetho-js-rhino/src/main/java/com/facebook/stetho/rhino/JsRuntimeReplFactoryBuilder.java
For external packages, the package name needs to be prefixed with `Packages.` per https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Rhino/Scripting_Java#External_Packages_and_Classes
Mostly fixes #405
> Fix importClass and importPackage not finding external classes

- stetho/src/main/java/com/facebook/stetho/inspector/protocol/module/Database.java
Since database drivers are such wide ranging third party code it
cannot be assumed that they exclusively throw SQLiteException but
instead could throw any manner of unknown RuntimeException and that
should not tear down the connection with chrome://inspect but, since
we are indeed a debug tool, should report sufficient debugging
information to diagnose the issue.
> Handle any runtime exception from a database driver

- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/ActivityTracker.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/ApplicationDescriptor.java
LeakCanary flags Stetho's ActivityTracker as a potential leak because it
does indeed have a path to the GC root that isn't already covered by the
many exclusions present in LeakCanary for legitimate Android use cases.
This is essentially a known flaw in LeakCanary in which unknown path to
GC roots are assumed to be leaks even if they are indeed consistent with
the normal object lifecycle (like in our case the strong reference is
removed when the activity is destroyed).
Working around this issue is trivial however and does indeed have the
effect of making our code look less suspicious of leaks in the first
place.
Closes #319
> Avoid false positive in LeakCanary

- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/AccessibilityNodeInfoWrapper.java
- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/ViewDescriptor.java
If you used Stetho in an app without the Android Support library as a dependency, the Accessibility Inspection feature would cause Stetho to crash when you tried to inspect an element.
This makes the dependency on the support library optional, and if it's not included in your app the accessibility inspection feature is simply disabled.
To do this, I had to go through all places we were accessibility AccessibilityNodeInfoCompat and make sure they were only used behind a check for the existence of this class.  To keep this check to be in as few places as possible, I moved all AccessibilityNodeInfo creation and recycling into the AccessibilityNodeInfoWrapper class, which are the bulk of the changes here.
> Fixed unexpected dependency on support library for Accessibility properties

- stetho/src/main/java/com/facebook/stetho/inspector/elements/android/ViewGroupDescriptor.java
This was implemented previously to get around an issue with overlays.
This was wrong and should be implemented by making overlays
non-focusable instead.
> Allow hitting empty viewgroups

- stetho/src/main/java/com/facebook/stetho/inspector/protocol/module/CSS.java
When deleting the value of a style property chrome sends back an empty string instead of a key with an empty value.
> Fix crash when stylesheet text is empty

- stetho-sample/src/main/AndroidManifest.xml
- stetho-sample/src/main/java/com/facebook/stetho/sample/IRCChatActivity.java
- stetho-sample/src/main/java/com/facebook/stetho/sample/IRCClientConnection.java
- stetho-sample/src/main/java/com/facebook/stetho/sample/IRCConnectActivity.java
- stetho-sample/src/main/java/com/facebook/stetho/sample/MainActivity.java
- stetho-sample/src/main/res/layout/irc_chat_activity.xml
- stetho-sample/src/main/res/layout/irc_connect_activity.xml
- stetho-sample/src/main/res/layout/irc_console_row.xml
- stetho-sample/src/main/res/layout/main_activity.xml
- stetho-sample/src/main/res/values/strings.xml
- stetho/src/main/java/com/facebook/stetho/inspector/network/NetworkEventReporter.java
- stetho/src/main/java/com/facebook/stetho/inspector/network/NetworkEventReporterImpl.java
- stetho/src/main/java/com/facebook/stetho/inspector/network/SimpleBinaryInspectorWebSocketFrame.java
- stetho/src/main/java/com/facebook/stetho/inspector/network/SimpleTextInspectorWebSocketFrame.java
- stetho/src/main/java/com/facebook/stetho/inspector/protocol/module/Network.java
Generally this PR is designed to add full websocket (and raw socket) support to NetworkEventReporter but also introduces an IRC client in stetho-sample to test/demonstrate the functionality.  This screenshot shows the system in action in chrome://inspect:
Partially addresses #498
> Add full websocket support to NetworkEventReporter

- stetho/src/main/java/com/facebook/stetho/Stetho.java
- stetho/src/main/java/com/facebook/stetho/inspector/database/ContentProviderDatabaseDriver.java
- stetho/src/main/java/com/facebook/stetho/inspector/database/DatabaseDriver2Adapter.java
- stetho/src/main/java/com/facebook/stetho/inspector/database/SqliteDatabaseDriver.java
- stetho/src/main/java/com/facebook/stetho/inspector/protocol/module/BaseDatabaseDriver.java
- stetho/src/main/java/com/facebook/stetho/inspector/protocol/module/Database.java
- stetho/src/main/java/com/facebook/stetho/inspector/protocol/module/DatabaseDescriptor.java
- stetho/src/main/java/com/facebook/stetho/inspector/protocol/module/DatabaseDriver.java
- stetho/src/main/java/com/facebook/stetho/inspector/protocol/module/DatabaseDriver2.java
The SqliteDatabaseDriver had to resort to counter intuitive hacks
to manually locate a database by its file name and didn't
properly handle deduplicating multiple databases with the same name.  As
we expanded flexibility we failed to address the possibility (nay,
likelihood) that this will occur and it would create very confusing
results for users.
This diff doesn't address the confusion in the UI (two database entries
of the same name can still occur) but it internally makes it possible to
treat them as separate databases and track their filenames separately.
It also makes it relatively straightforward to fix the uniqueness of the
user visible naming by introducing a "context" parameter to
DatabaseDescriptor which would be used in the case of name ambiguity.
This diff addresses concerns …
> Fix database id mapping to remove guesswork hacks

- stetho-okhttp3/src/main/java/com/facebook/stetho/okhttp3/StethoInterceptor.java
`Interceptor.Chain.connection()` was [marked nullable](https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/Interceptor.java#L38) in OkHttp 3.8.0. 
In `StethoInterceptor` we retrieve a connection and don't check for `null`. This causes Stetho to crash when calling [`OkHttpInspectorResponse.connectionId()`](https://github.com/facebook/stetho/blob/master/stetho-okhttp3/src/main/java/com/facebook/stetho/okhttp3/StethoInterceptor.java#L226) when a connection is not present. 
Addresses #541
> Null check Interceptor.Chain.connection().

- stetho/src/main/java/com/facebook/stetho/websocket/Frame.java
fix payloadData length error when it's length is more than 0xffff
> fix payloadData length error

- stetho-js-rhino/README.md
The first use, the developer may not know what type jsRuntimeBuilder.
> Improve README.md

- README.md
The MyApplication Java class must be added to the AndroidManifest.xml, otherwise there will be no "Inspect" button that appears in chrome://inspect/#devices
Add this explanation in the documentation of Readme.md
> Fix issue #480 : Documentation to add MyApplication to AndroidManifest.xml

- stetho-okhttp/src/main/java/com/facebook/stetho/okhttp/StethoInterceptor.java
- stetho-okhttp/src/test/java/com/facebook/stetho/okhttp/StethoInterceptorTest.java
- stetho-okhttp3/src/main/java/com/facebook/stetho/okhttp3/StethoInterceptor.java
- stetho-okhttp3/src/test/java/com/facebook/stetho/okhttp3/StethoInterceptorTest.java
Previously this would yield a NullPointerException and was not very
discoverable/actionable for users.
Closes #580
> Improve error message when addInterceptor is used instead of addNetworkInterceptor

- stetho/src/main/java/com/facebook/stetho/inspector/network/NetworkEventReporter.java
Obvious typo, a misspelled function name.
> Fixed a typo in the websocket flow diagram

- stetho-js-rhino/README.md
The anchor formatting was broken, now fixed. 
The syntax of the linked issue does not seem to work, hence replaced by actual link.
> Fixed anchor formatting + issue link

- stetho/src/main/java/com/facebook/stetho/inspector/network/NetworkEventReporterImpl.java
Now the session information can be displayed correctly
> Fix the missing notification on WebSocket handshake response received

- stetho/build.gradle
These files would conflict with any other version of the support
library the user tried to add and are not otherwise required or
important for Stetho to function.
Closes #566
> Fix fatjar compilation including android support library R.class files

- scripts/stetho_open.py
dumpapp stopped working for me because /proc/net/unix has two spaces to separate state from inode when the inode length is less than the maximum inode length (123 vs 1234).
E.g.:
```
00000000: 00000002 00000000 00010000 0001 01 76292 /dev/socket/cryptd
00000000: 00000002 00000000 00010000 0001 01  3836 @stetho_com.facebook.wakizashi_devtools_remote
```
We should be parsing this with `\s+` and not a simple space since the output date is a table that is formatted to look like columns in the print out.
I tested this by running dumpapp in a situation like the one mentioned above.
> Fix the way /proc/net/unix is being parsed

- scripts/stetho_open.py
There are multiple ways to set the adb server connection information in the
environment. This commit adds support for `ADB_SERVER_SOCKET`.
Set a valid server socket environment variable:
```
$ export ADB_SERVER_SOCKET=tcp:localhost:5038
$ adb devices
List of devices attached
* daemon not running; starting now at tcp:localhost:5038
* daemon started successfully
```
Now dumpapp doesn't fail anymore:
```
$ scripts/dumpapp
Failure to target device None: no devices/emulators found
```
It does fail when the socket spec is invalid/unsupported:
```
$ export ADB_SERVER_SOCKET=nope
$ scripts/dumpapp
...
stetho_open.HumanReadableError: Invalid or unsupported socket spec 'nope' specified in ADB_SERVER_SOCKET.
```
```
$ export ADB_SERVER_SOCKET=tcp:localhost:abc
$ scripts/dumpapp
... …
```
> Add support for ADB_SERVER_SOCKET in dumpapp

- stetho/src/main/java/com/facebook/stetho/dumpapp/plugins/SharedPreferencesDumperPlugin.java
- stetho/src/main/java/com/facebook/stetho/inspector/domstorage/SharedPreferencesHelper.java
- stetho/src/main/java/com/facebook/stetho/inspector/protocol/module/DOMStorage.java
This PR solves #595 . Currently all preferences are unsorted and hard to find. This patch will make preferences sort by key alphabetically.
> Sorts SharedPreferences entries

- README.md
Recently there was a change in groovy code that replaces `compile`with `implementation`, which will soon be standard. To keep this great repro future proof I have added these minor changes.
> updated to new groovy coding standards

- stetho/src/main/java/com/facebook/stetho/Stetho.java
- stetho/src/test/java/com/facebook/stetho/PluginBuilderTest.java
and DefaultInspectorModulesBuilder by fixing PluginBuilder.remove(). Tests are added.
> Made .remove() working for DefaultDumperPluginsBuilder 

- stetho/src/main/java/com/facebook/stetho/inspector/protocol/module/Page.java
As per @longinoa suggestion in #602, I've added additional constructor to Page and made a fallback to existing banner. It's still is a constant `String` so no packaging changes required.
> Fixes #602 - allow to change console banner

- stetho/src/main/java/com/facebook/stetho/inspector/protocol/module/Runtime.java
Otherwise class can't be extended and method overridden (Currently only @ChromeDevtoolsMethod methods are detected and method needed to be overridden because look-up is done only in declared methods)
Override of Stetho's default domain classes might be need if issues like following are found: https://github.com/facebook/stetho/issues/611
> Remove private class (CallFunctionOnResponse) from signature of the public method

- stetho/src/main/java/com/facebook/stetho/inspector/MethodDispatcher.java
look-up for methods with @ChromeDevtoolsMethod not only in the class itself, but also in the parent classes.
Override of Stetho's default domain classes might be need if issues like following are found: #611 
Work-around with `fun method = super.method()` could be used, but in it's verbose, inconvenient and in some edge cases like following can't be implemented: https://github.com/facebook/stetho/pull/612
> Added ability for domain classes to be inherited

- stetho/src/main/java/com/facebook/stetho/inspector/protocol/module/Runtime.java
I am developing debugger for [J2V8](https://github.com/eclipsesource/J2V8), which uses Stetho for communication over Chrome  DevTools protocol. Besides implementing Debugger domain I need to add local v8 variables to `Runtime` by static `.mapObject()` in order them to be visible in the Chrome Debugger UI.
The problem, that `@ChromeDevtoolsMethod` `.releaseObject()` method is not called by Chrome DevTools and I want to remove objects stored in the session manually in order to avoid memory leaks and possible OOM errors. That's why I would like to have static method to remove them from session. Some work-around are possible already now, but it makes sense for me to have it because `static` _counter-part_ for adding object is exists - `.mapObject()` .
> Added static method for removing objects previously added by .mapObject()

- stetho/build.gradle
afterEvaluate and configurations.compile are no longer valid in the same
context and needed to be updated to go back to more traditional Gradle
DSL features.
> Fix Stetho fatjar after gradle upgrade

- scripts/stetho_open.py
Some adb server only listens at IPv6 address family.
This change will first attempt to connect with IPv4 and if it fails then switch to IPv6.
> stetho_open connect also consider IPv6

- index.md
Here at Meta Open Source, we've been creating short-form videos to explain Meta OSS projects in the simplest terms possible. We started embedding these videos into project pages as you can see in [Docusaurus home page](https://docusaurus.io/), [Recoil](https://recoiljs.org/), [Litho](https://fblitho.com/), [Hydra](https://hydra.cc/), etc.
> docs: adding ELI5 video to the home page

- stetho/src/main/java/com/facebook/stetho/common/ProcessUtil.java
- stetho/src/main/java/com/facebook/stetho/server/AddressNameHelper.java
For supporting that, adding non-default user id to stetho socket name, so they can be distinguished.
Currently, Stetho uses socket address in form `stetho_<package>_devtools_remote`.
If two instances of the same app are running (e.g. in dual app mode), one of them will open socket successfully, but the second app will fail:
```
$ adb logcat -s 'stetho:*'
07-11 15:04:34.942 28329 28580 I stetho  : Listening on @stetho_com.myapp_devtools_remote
07-11 15:04:57.951 29513 29827 E stetho  : Could not start Stetho server: main
```
Adding user id for non-default (non-0) user into socket address, so both sockets can be opened at the same time:
```
$ adb logcat -s 'stetho:*'
07-11 15:07:09.405 31796 32606 I stetho  : Listening on @stetho_com.myapp_devtools_remote
07-11 15:07:14.751 31954   654 I …
```
> Support running Stetho in multi-user Android environments
